#!/bin/sh
# Tests/93-model-switch.test.sh - changing the model of an open conversation, in place.
#
# WHAT A MODEL IS DECIDES WHAT HAS TO HAPPEN TO CHANGE IT, and that is the whole content of this
# file. A GGUF model is a llama-server this app owns, named in the agent's argv only as a port; an
# MLX model is a directory the agent maps itself, named in its argv; the on-device model is a
# backend flag. So one cell of the matrix - gguf to gguf - is a server restart under an agent that
# never notices, and every other cell has to REPLACE the agent process, which the app does by
# re-injecting states["config"] and letting the element stop the old one, spawn the new one and
# re-prime it from the transcript on screen.
#
# Those two mechanisms fail in opposite ways, silently, and the assertions here are mostly about
# which one ran: a cell that re-injects when it should have restarted leaves the conversation on a
# fresh agent with no history; a cell that restarts when it should have re-injected leaves the
# window titled with a model that is not answering it. Neither shows up as an error.
#
# The engine work is driven through sw(), which stubs the four things that touch the machine
# (launching llama-server, stopping one, claiming a port, probing Apple Intelligence). Everything
# else is real - the transport JSON is generated by the same builder the app ships, so the argv
# asserted below is the argv a window would actually get.
#
# POSIX sh only. Validate with "sh -n", never "bash -n".
. "${OMCTEST_LIB:?set OMCTEST_LIB, or run via: appletbuilder test}"
. "$OMCTEST_TESTS/lib.test.cadabra.sh"

cad_import_ids aichat.chat.engine.library.sh CE_
cad_import_ids aichat.library.sh BASE_
cad_import_ids aichat.history.library.sh HL_
CHAT_ID=1
# The ids this file writes through, asserted as literals so a rename reports itself once here
# instead of turning every assertion below it vacuously true.
check "the chat element is the id the switch injects into" "1"   "$CE_CHAT_ELEMENT_ID"
check "and the model bar is the button it renames"          "542" "$CE_CHAT_MODEL_BTN_ID"

lib() { cad_call_lib aichat.library.sh "$@"; }
# The loading overlay is inserted into declared slot 550 and removed again, so its own id only
# exists at runtime. Declared here rather than silently tripping the undeclared-id check.
# The same for the Allow a Folder... button, put into slot 548 after a load and a switch.
ui_declare_ids "$BASE_CHAT_OVERLAY_ELEM_ID" "$HL_CAD_SUMMARIZE_PICKER_ID" "$(cad_lib_var allow_folder_button_id aichat.allow.folder.library.sh)" "$(cad_lib_var allow_packs_button_id aichat.allow.folder.library.sh)"

# ---------------------------------------------------------------------------
# Fixtures: models that EXIST, because model_engine tests the filesystem rather than the name.
MODELS="$OMCTEST_WORK/models"
/bin/mkdir -p "$MODELS"
GGUF="$MODELS/Tiny-Q4_K_M.gguf"
OTHER="$MODELS/Other-Q5_K_S.gguf"
/usr/bin/head -c 4096 /dev/zero > "$GGUF"
/usr/bin/head -c 4096 /dev/zero > "$OTHER"
MLXDIR="$MODELS/Mlx-Test-Model"
OTHERMLX="$MODELS/Mlx-Other-Model"
for d in "$MLXDIR" "$OTHERMLX"; do
    /bin/mkdir -p "$d"
    printf '{}' > "$d/config.json"
    /usr/bin/head -c 512 /dev/zero > "$d/model.safetensors"
done
# The PHYSICAL paths, which is what the mlx branch stamps and injects: under the harness $TMPDIR
# that is a real difference (/var -> /private/var), and asserting the input path would pass here
# and fail for the reason the resolution exists.
MLXREAL=$(cd "$MLXDIR" && pwd -P)
OTHERMLXREAL=$(cd "$OTHERMLX" && pwd -P)
FOUNDATION=$(cad_lib_var FOUNDATION_MODEL_ID aichat.model.library.sh)
check "the on-device sentinel is what the picker passes" "foundation:apple-on-device" "$FOUNDATION"

# A window uuid that is not this file's own: the picker's OK runs in the PICKER's window and acts
# on a chat window somewhere else, and a test using one uuid for both could not tell them apart.
SWIN="OMCTEST-switch-$$"

# ---------------------------------------------------------------------------
# sw <function> [args...] - the engine library with everything that touches the machine stubbed.
#
# NOT OPTIONAL, for the same reason 95's eng() is not: the real launch would spawn a llama-server
# against the developer's own bundle, and the real reaper walks `ps` for paths under the REAL
# $OMC_APP_BUNDLE_PATH, which on this machine is their running copy of the app.
#
# Each stub RECORDS rather than merely returning, because the cells differ in which of them runs
# and in what order - the two failures this file exists to catch are a launch that should not have
# happened and a stop that happened too early.
SW_LOG="$OMCTEST_WORK/switch-calls.log"
: > "$SW_LOG"

# Whether the element has already been given its new transport at the moment a stub is called.
# This is how "stopped AFTER the injection" is asserted: the order matters because the old agent
# may be mid-request against the outgoing server, and killing it first turns a switch into an
# error item in the transcript.
sw_seen_config() {
    if /usr/bin/grep -q 'omc_set_state config' "$OMCTEST_UI/journal.tsv" 2>/dev/null; then
        printf 'after-inject\n'
    else
        printf 'before-inject\n'
    fi
}

sw() {
    ( . "$OMC_APP_BUNDLE_PATH/Contents/Resources/Scripts/aichat.chat.engine.library.sh" >/dev/null 2>&1
      prefs="${CAD_PREFS_OVERRIDE:-$OMCTEST_WORK/no-such-registry.plist}"
      stop_orphaned_servers() { :; }
      reap_orphaned_bundle_processes() { :; }
      launch_model_on_port() {
          # $4 is the engine this window is about to stop, which only the cell that launches while
          # its predecessor is still resident has one of, and $5 is the window that can be proven
          # to own it. Recorded because passing them is the whole difference between a server sized
          # for the memory it will have and one sized for the memory it has during the handover.
          printf 'launch\t%s\t%s\t%s\t%s\n' "$1" "$3" "$4" "$5" >> "$SW_LOG"
          LAUNCHED_MODEL_LABEL=$(/usr/bin/basename "$1" .gguf)
          return "${STUB_LAUNCH_RC:-0}"
      }
      stop_window_server() {
          printf 'stop\t%s\t%s\n' "$1" "$(sw_seen_config)" >> "$SW_LOG"
          return 0
      }
      find_free_port_in() { printf '%s\n' "${STUB_PORT:-8199}"; }
      foundation_probe() { printf '%s\t%s\n' "${STUB_FM:-available}" "the on-device model is ready"; }
      # The one failure with a server already running behind it, and the only way to produce it
      # without a machine: a transport builder that comes back empty.
      if [ "${STUB_EMPTY_JSON:-0}" = "1" ]; then
          aichat_acp_transport_json() { :; }
      fi
      "$@" )
}

sw_reset() { # a clean journal, a clean call log, and every stub back to "it works"
    : > "$SW_LOG"
    cad_journal_reset
    alerts_reset
    alert_answers_reset
    # NOT settable as `STUB_x=1 sw ...`: a variable assignment prefixing a FUNCTION call PERSISTS
    # in the shell after it returns (unlike one prefixing a command), so a section that forces a
    # failure would go on forcing it for every section below. Set them after sw_reset, deliberately.
    STUB_LAUNCH_RC=0
    STUB_PORT=8199
    STUB_FM=available
    STUB_EMPTY_JSON=0
}
sw_calls()      { /usr/bin/cut -f1 "$SW_LOG" | /usr/bin/tr '\n' ' ' | /usr/bin/sed 's/ *$//'; }
sw_launch_port() { /usr/bin/awk -F'\t' '$1 == "launch" { print $3 }' "$SW_LOG" | /usr/bin/tail -n 1; }
sw_launch_model() { /usr/bin/awk -F'\t' '$1 == "launch" { print $2 }' "$SW_LOG" | /usr/bin/tail -n 1; }
sw_launch_retiring() { /usr/bin/awk -F'\t' '$1 == "launch" { print $4 }' "$SW_LOG" | /usr/bin/tail -n 1; }
sw_launch_retiring_win() { /usr/bin/awk -F'\t' '$1 == "launch" { print $5 }' "$SW_LOG" | /usr/bin/tail -n 1; }
sw_stop_when()  { /usr/bin/awk -F'\t' '$1 == "stop" { print $3 }' "$SW_LOG" | /usr/bin/tail -n 1; }
# What the element was actually handed, IN THE WINDOW BEING SWITCHED. cad_journal answers for a
# view id across every window in the file, and this file drives a switch aimed at $SWIN from a
# picker running somewhere else - so a bare read could not tell "injected into the chat window"
# from "injected into whatever window happened to write last", which is the one mistake a
# window-scoped handler makes. Field 1 of the journal is the window uuid.
sw_win_journal() { # <view-id>
    /usr/bin/awk -F'\t' -v w="$SWIN" -v t="$1" '$1 == w && $2 == t { sub(/ $/, "", $3); print $3 }' \
        "$OMCTEST_UI/journal.tsv"
}
sw_config()     { sw_win_journal "$CHAT_ID" | /usr/bin/sed -n 's/^omc_set_state config //p' | /usr/bin/tail -n 1; }
sw_configs()    { sw_win_journal "$CHAT_ID" | /usr/bin/grep -c 'omc_set_state config .' | /usr/bin/tr -d ' '; }
sw_bar()        { sw_win_journal "$CE_CHAT_MODEL_BTN_ID" | /usr/bin/sed -n 's/^omc_set_property title //p' | /usr/bin/tail -n 1; }
sw_led()        { sw_win_journal "$CHAT_ID" | /usr/bin/grep 'omc_set_state lead .'; }
sw_appended()   { sw_win_journal "$CHAT_ID" | /usr/bin/grep 'omc_set_state append .'; }
# The MCP config generated for this window's session, which the tools decision creates or removes.
sw_mcp_config() { printf '%s\n' "$HOME/Library/Application Support/Cadabra/Sessions/$SWIN/mcp-config.json"; }

# What the registry says a server was launched FOR. Defined here rather than spelled as a plister
# call at four assertion sites, and read through the same $prefs the library writes.
chat_switch_probe_dialog() { # <server-pid>
    "$plister" get string "$prefs" "/server-info/$1/dialog" 2>/dev/null
}

# A conversation on disk, so a marker has somewhere to be recorded.
cad_hist="$HOME/Library/Application Support/Cadabra/History"
cad_mk_session() { # <sid>
    /bin/mkdir -p "$cad_hist/$1"
    : > "$cad_hist/$1/journal.jsonl"
    printf '{"id": "%s", "created": "2026-08-21", "modelPath": "%s"}\n' "$1" "$MLXREAL" \
        > "$cad_hist/$1/meta.json"
}

# A window running one engine, with nothing held and nothing bound.
# <model> <port-or-empty> [tools-decision]
sw_window() {
    cad_pb_set "aichatv2_modelpath_$SWIN" "$1"
    cad_pb_set "aichatv2_agent_$SWIN" ""
    cad_pb_set "aichatv2_port_$SWIN" "$2"
    cad_pb_set "aichatv2_tools_$SWIN" "${3:-false}"
    cad_pb_set "aichatv2_open_$SWIN" "1"
    cad_pb_set "aichatv2_session_$SWIN" ""
    cad_pb_set "aichatv2_resume_pending_$SWIN" ""
    cad_pb_set "aichatv2_pending_markers_$SWIN" ""
}

# ---------------------------------------------------------------------------
section "MLX to MLX: the conversation is handed to another agent, not another server"
# The case that was refused outright until now, and the one the user hit: two MLX models, no
# server anywhere. The whole switch is the argv, so the ONLY evidence it happened is the injected
# config - and the only evidence it was done right is that nothing was launched or stopped.
sw_reset
sw_window "$MLXREAL" ""
sw chat_engine_switch "$SWIN" "$OTHERMLX" false
check "the switch succeeds"              "0" "$?"
check "the element is given a transport" "1" "$(sw_configs)"
check "  naming the new model directory" "1" "$(cad_has "$(sw_config)" "\"--model\", \"$OTHERMLXREAL\"")"
check "  and not the old one"            "0" "$(cad_has "$(sw_config)" "\"$MLXREAL\"")"
check "nothing is launched or stopped"   ""  "$(sw_calls)"
check "the window is stamped with it"    "$OTHERMLXREAL" "$(cad_pb_get "aichatv2_modelpath_$SWIN")"
check "  and claims no port"             ""  "$(cad_pb_get "aichatv2_port_$SWIN")"
check "the model bar names it"           "Mlx-Other-Model" "$(sw_bar)"
check "and the overlay was raised"       "1" "$(cad_has "$(cad_journal "$BASE_CHAT_OVERLAY_SLOT_ID")" "omc_insert_element")"
check "  then dropped again"             "1" "$(cad_has "$(cad_journal "$BASE_CHAT_OVERLAY_ELEM_ID")" "omc_remove_element")"

# ---------------------------------------------------------------------------
section "GGUF to MLX: the server is stopped, and only after the agent has been replaced"
# ORDER IS THE ASSERTION. The injection is what ends the old agent; until it returns, that agent
# may be mid-request against this server. Stopping the server first fails that request, and the
# failure reaches the transcript as an error item and the journal as an error entry - moments
# before the agent was going to be replaced anyway.
sw_reset
sw_window "$GGUF" "8151"
sw chat_engine_switch "$SWIN" "$MLXDIR" false
check "the switch succeeds"                 "0" "$?"
check "the element is given a transport"    "1" "$(sw_configs)"
check "  naming the model directory"        "1" "$(cad_has "$(sw_config)" "\"--model\", \"$MLXREAL\"")"
check "  and no base URL at all"            "0" "$(cad_has "$(sw_config)" "base-url")"
check "this window's server is stopped"     "stop" "$(sw_calls)"
check "  AFTER the element was reconfigured" "after-inject" "$(sw_stop_when)"
check "and the port claim is released"      ""  "$(cad_pb_get "aichatv2_port_$SWIN")"

section "  and a preparation that fails stops nothing and injects nothing"
# The old engine is still answering: nothing has been stopped yet, so a failure here costs the
# user nothing but an alert.
sw_reset
sw_window "$GGUF" "8151"
STUB_EMPTY_JSON=1
sw chat_engine_switch "$SWIN" "$MLXDIR" false
check "the switch reports failure"       "1" "$?"
check "nothing was injected"             "0" "$(sw_configs)"
check "  and no server was stopped"      ""  "$(sw_calls)"
check "the window keeps its model"       "$GGUF" "$(cad_pb_get "aichatv2_modelpath_$SWIN")"
check "  and its port"                   "8151" "$(cad_pb_get "aichatv2_port_$SWIN")"
check "the user is told"                 "1" "$(alerts_count)"

# ---------------------------------------------------------------------------
section "MLX to GGUF: a server has to exist before the new agent asks for it"
# The agent health-checks llama-server during session/new and gives up in about seven seconds,
# which is far less than a model load - so the launch comes FIRST and the injection second. Which
# means the outgoing MLX agent is still holding its weights while the server is sized, and the
# sizing has to be told so: a server keeps its --fit decision for its whole life, so charging it
# for memory that is freed seconds later is a context it never gets back.
sw_reset
sw_window "$MLXREAL" ""
STUB_PORT=8177
sw chat_engine_switch "$SWIN" "$GGUF" false
check "the switch succeeds"                "0" "$?"
check "a server is launched, none stopped" "launch" "$(sw_calls)"
check "  for the chosen model"             "$GGUF" "$(sw_launch_model)"
check "  on the port this window claimed"  "8177"  "$(sw_launch_port)"
check "  told which engine is retiring"    "$MLXREAL" "$(sw_launch_retiring)"
# Tools were OFF for this window, so its agent carries no --mcp-config and cannot be picked out of
# the process table. Claiming otherwise would let the sizing discount another window's engine.
check "  but not claimed to be identifiable" "" "$(sw_launch_retiring_win)"
check "the port is stamped for the window" "8177"  "$(cad_pb_get "aichatv2_port_$SWIN")"
check "the element is given a transport"   "1" "$(sw_configs)"
check "  pointed at that port"             "1" "$(cad_has "$(sw_config)" '"--base-url", "http://127.0.0.1:8177/v1"')"
check "  and carrying no --model"          "0" "$(cad_has "$(sw_config)" '"--model"')"
check "the model bar names the new model"  "Tiny-Q4_K_M" "$(sw_bar)"

section "  and a window running tools can prove which agent is its own"
# With tools on the outgoing agent carries --mcp-config .../Sessions/<win>/, which no other
# window's argv can contain. Passing the window is what lets the scan read "not found" as "my agent
# is already gone" rather than falling back to whichever engine happens to run the same model.
sw_reset
sw_window "$MLXREAL" "" true
STUB_PORT=8178
sw chat_engine_switch "$SWIN" "$GGUF" true
check "the switch succeeds"                "0" "$?"
check "the retiring engine is named"       "$MLXREAL" "$(sw_launch_retiring)"
check "  and so is the window that owns it" "$SWIN" "$(sw_launch_retiring_win)"

section "  a launch that never comes up leaves the window on the model it had"
sw_reset
sw_window "$MLXREAL" ""
STUB_LAUNCH_RC=11
STUB_PORT=8177
sw chat_engine_switch "$SWIN" "$GGUF" false
check "the switch reports failure"    "1" "$?"
check "nothing was injected"          "0" "$(sw_configs)"
check "the model stamp is put back"   "$MLXREAL" "$(cad_pb_get "aichatv2_modelpath_$SWIN")"
check "  and the port is unclaimed"   ""  "$(cad_pb_get "aichatv2_port_$SWIN")"

section "  and a launch that DID come up is stopped when the transport is refused"
# THE LEAK THIS EXISTS TO CLOSE. The server is up and registered to this window; nothing will ever
# talk to it. The close handler stops one server per window, so a later gguf-to-gguf switch on a
# fresh port would strand this one until the app quits.
sw_reset
sw_window "$MLXREAL" ""
STUB_EMPTY_JSON=1
STUB_PORT=8177
sw chat_engine_switch "$SWIN" "$GGUF" false
check "the switch reports failure"        "1" "$?"
check "the server it started is stopped"  "launch stop" "$(sw_calls)"
check "  with nothing having been injected" "before-inject" "$(sw_stop_when)"
check "and the port is unclaimed"         ""  "$(cad_pb_get "aichatv2_port_$SWIN")"
check "the window keeps its model"        "$MLXREAL" "$(cad_pb_get "aichatv2_modelpath_$SWIN")"

# ---------------------------------------------------------------------------
section "GGUF to GGUF: the one cell with nothing to re-inject"
# The agent's argv names the PORT, not the model, and its conversation array survives a server
# restart underneath it - which is the semantics this cell wants. Re-injecting here would throw
# that away and re-prime a fresh agent for no reason.
sw_reset
sw_window "$GGUF" "8151"
sw chat_engine_switch "$SWIN" "$OTHER" false
check "the switch succeeds"              "0" "$?"
check "the server restarts, nothing else" "launch" "$(sw_calls)"
check "  on the window's own port"       "8151" "$(sw_launch_port)"
# Nothing of this window's is retiring here: the outgoing server on this port was TERMed and
# waited out by the launch itself, and the agent that survives holds no weights of its own. Naming
# a retiring engine here would discount a model that is genuinely gone and over-commit the GPU.
check "  and nothing is retiring under it" "" "$(sw_launch_retiring)"
check "NOTHING is injected"              "0" "$(sw_configs)"
check "the window keeps that port"       "8151" "$(cad_pb_get "aichatv2_port_$SWIN")"
check "and is stamped with the new model" "$OTHER" "$(cad_pb_get "aichatv2_modelpath_$SWIN")"
check "the model bar names it"           "Other-Q5_K_S" "$(sw_bar)"

# ---------------------------------------------------------------------------
section "the on-device model, both ways"
sw_reset
sw_window "$MLXREAL" ""
sw chat_engine_switch "$SWIN" "$FOUNDATION" false
check "switching to it succeeds"         "0" "$?"
check "the element is given a transport" "1" "$(sw_configs)"
check "  naming the backend"             "1" "$(cad_has "$(sw_config)" '"--backend", "foundation"')"
check "  and no model at all"            "0" "$(cad_has "$(sw_config)" '"--model"')"
check "nothing is launched or stopped"   ""  "$(sw_calls)"
check "it is not remembered as a recent" "0" \
    "$(cad_has "$(cad_call_lib aichat.model.library.sh model_recents_list)" "$FOUNDATION")"

section "  and when Apple Intelligence is off, the window keeps what it had"
# THE LAST AVAILABILITY GATE. The picker's probe is minutes old by the time a switch runs, and
# the setting can be turned off in between.
sw_reset
sw_window "$MLXREAL" ""
STUB_FM=appleIntelligenceOff
sw chat_engine_switch "$SWIN" "$FOUNDATION" false
check "the switch reports failure"     "1" "$?"
check "nothing was injected"           "0" "$(sw_configs)"
check "the user is told"               "1" "$(alerts_count)"
check "the window keeps its model"     "$MLXREAL" "$(cad_pb_get "aichatv2_modelpath_$SWIN")"

section "switching FROM the on-device model is an ordinary respawn"
sw_reset
sw_window "$FOUNDATION" ""
sw chat_engine_switch "$SWIN" "$MLXDIR" false
check "the switch succeeds"              "0" "$?"
check "  naming the model directory"     "1" "$(cad_has "$(sw_config)" "\"--model\", \"$MLXREAL\"")"
check "nothing is launched or stopped"   ""  "$(sw_calls)"

# ---------------------------------------------------------------------------
section "what the switch refuses"
sw_reset
cad_pb_set "aichatv2_modelpath_$SWIN" ""
cad_pb_set "aichatv2_agent_$SWIN" "Claude Code"
sw chat_engine_switch "$SWIN" "$MLXDIR" false
check "an agent's conversation is not moved to a local model" "1" "$?"
check "  nothing is injected"       "0" "$(sw_configs)"
check "  and the agent stamp stands" "Claude Code" "$(cad_pb_get "aichatv2_agent_$SWIN")"
check "  and no model is stamped over it" "" "$(cad_pb_get "aichatv2_modelpath_$SWIN")"

sw_reset
sw_window "$MLXREAL" ""
sw chat_engine_switch "$SWIN" "$MODELS/gone.gguf" false
check "a target that is not a model is refused" "1" "$?"
check "  with an alert"             "1" "$(alerts_count)"
check "  naming what was expected"  "1" "$(alerts_mention "config.json")"
check "  nothing is injected"       "0" "$(sw_configs)"
check "  and the window is untouched" "$MLXREAL" "$(cad_pb_get "aichatv2_modelpath_$SWIN")"

section "a current model deleted from disk is still a window that can be switched"
# The window is RUNNING that model - the file being gone does not stop the agent that mapped it -
# so the current side of the matrix is read from what the window HAS, never from re-detecting the
# engine of a path that no longer exists.
sw_reset
sw_window "$MODELS/deleted-since.gguf" "8151"
sw chat_engine_switch "$SWIN" "$MLXDIR" false
check "the switch succeeds"               "0" "$?"
check "  and treats it as the server window it is" "stop" "$(sw_calls)"
check "  reconfiguring the element"       "1" "$(sw_configs)"

# ---------------------------------------------------------------------------
section "the handover is recorded where it happened"
# A switch keeps the SAME session, and meta.json names the model the session started with - so
# without this line the transcript has two stretches of assistant turns by different models and
# nothing saying where one ends.
sw_reset
sw_window "$MLXREAL" ""
cad_mk_session "20260821T000000Z-switch"
cad_pb_set "aichatv2_session_$SWIN" "20260821T000000Z-switch"
sw chat_engine_switch "$SWIN" "$OTHERMLX" false
check "a bound conversation is told at once" "1" "$(cad_has "$(sw_appended)" '"kind": "modelChanged"')"
check "  naming the model taking over"       "1" "$(cad_has "$(sw_appended)" "Mlx-Other-Model")"
check "  and it is in the journal"           "1" \
    "$(cad_has "$(/bin/cat "$cad_hist/20260821T000000Z-switch/journal.jsonl")" '"kind": "modelChanged"')"
check "  while the window title is left alone"    "0" "$(ui_calls omc_window)"

section "  a switch before the first message queues behind the line that opens it"
# Nothing has been said into this window yet, so the opening marker is still held for the first
# message. The switch joins it there instead of being recorded on its own - a brand-new window has
# no session directory to record into, and both lines belong in front of that first message.
sw_reset
sw_window "$MLXREAL" ""
cad_mk_session "20260821T000002Z-held"
cad_pb_set "aichatv2_session_$SWIN" "20260821T000002Z-held"
cad_call_lib aichat.history.library.sh history_marker_lead "$SWIN" "$CHAT_ID" started "Mlx-Test-Model"
cad_journal_reset
sw chat_engine_switch "$SWIN" "$OTHERMLX" false
held=$(cad_pb_get "aichatv2_pending_markers_$SWIN")
check "the window now holds two lines"   "2" "$(printf '%s\n' "$held" | /usr/bin/grep -c '"type": "sessionEvent"')"
check "  the second being the handover"  "1" "$(cad_has "$held" '"kind": "modelChanged"')"
check "  published to the element"       "1" "$(cad_has "$(sw_led)" '"kind": "modelChanged"')"
# Held, not shown - and this window HAS a session to record into, so the queue is genuinely what
# refused to record rather than the armed-resume floor underneath it.
check "and nothing is put on screen"     ""  "$(sw_appended)"
check "  nor recorded yet"               "0" \
    "$(cad_has "$(/bin/cat "$cad_hist/20260821T000002Z-held/journal.jsonl" 2>/dev/null)" 'modelChanged')"

section "  and a conversation only opened for reading records nothing yet"
# The armed resume is the floor under the queue: a window handed a conversation it has not been
# spoken to shows no marker and queues none, and a switch must not write into a transcript
# nothing has happened in.
sw_reset
sw_window "$MLXREAL" ""
cad_mk_session "20260821T000001Z-read"
cad_pb_set "aichatv2_session_$SWIN" "20260821T000001Z-read"
cad_pb_set "aichatv2_resume_pending_$SWIN" "20260821T000001Z-read"
sw chat_engine_switch "$SWIN" "$OTHERMLX" false
check "the switch still happens"      "1" "$(sw_configs)"
check "  but nothing is appended"     ""  "$(sw_appended)"
check "  and the journal is untouched" "0" \
    "$(cad_has "$(/bin/cat "$cad_hist/20260821T000001Z-read/journal.jsonl")" 'modelChanged')"

# ---------------------------------------------------------------------------
section "the handler is a handoff, and it validates one"
# The keys are cleared as they are read, so nothing can fire twice - and a window that closed
# while its model was being chosen must not have an engine prepared for it.
chains_reset
sw_reset
sw_window "$MLXREAL" ""
cad_pb_set "aichatv2_switch_target" "$SWIN"
cad_pb_set "aichatv2_switch_tools" "false"
"$OMC_OMC_SUPPORT_PATH/pasteboard" AICHATV2_MODEL_PATH set "$OTHERMLX"
omc_run aichat.chat.switch.model
check_status "the handler succeeds" 0
check "the element is reconfigured"   "1" "$(sw_configs)"
check "the target is consumed"        ""  "$(cad_pb_get aichatv2_switch_target)"
check "  and so is the tools decision" "" "$(cad_pb_get aichatv2_switch_tools)"
check "  and the model handoff"       ""  "$("$OMC_OMC_SUPPORT_PATH/pasteboard" AICHATV2_MODEL_PATH get)"

sw_reset
sw_window "$MLXREAL" ""
cad_pb_set "aichatv2_open_$SWIN" ""
cad_pb_set "aichatv2_switch_target" "$SWIN"
"$OMC_OMC_SUPPORT_PATH/pasteboard" AICHATV2_MODEL_PATH set "$OTHERMLX"
omc_run aichat.chat.switch.model
check_status "a closed window is not switched" 0
check "  nothing is injected"  "0" "$(sw_configs)"
check "  and it is not stamped" "$MLXREAL" "$(cad_pb_get "aichatv2_modelpath_$SWIN")"

sw_reset
cad_pb_set "aichatv2_switch_target" ""
omc_run aichat.chat.switch.model
check_status "and no handoff at all is quiet" 0
check "  nothing is injected" "0" "$(sw_configs)"

# ---------------------------------------------------------------------------
section "the picker routes every pair of local engines to the switch"
# ONE GESTURE, TWO DESTINATIONS, and the stamps decide which: the model bar's button arms the
# same handoff whatever the window is running. What changed is that the destination is no longer
# gguf-to-gguf only.
sw_arm_pick() { # <target-model> <tools>
    cad_pb_set "aichatv2_switcharm_$OMC_ACTIONUI_WINDOW_UUID" "$SWIN|$(/bin/date +%s)"
    omc_table_cell 10 5 "$1"
    omc_control 30 "$2"
}
for pair in "$MLXREAL|$OTHERMLX|MLX to MLX" "$GGUF|$MLXDIR|GGUF to MLX" "$MLXREAL|$GGUF|MLX to GGUF" "$GGUF|$OTHER|GGUF to GGUF"; do
    current=${pair%%|*}
    rest=${pair#*|}
    target=${rest%%|*}
    label=${rest#*|}
    chains_reset
    sw_reset
    case "$current" in *.gguf) sw_window "$current" "8151" ;; *) sw_window "$current" "" ;; esac
    sw_arm_pick "$target" false
    omc_run aichat.select.local.model.ok
    check "$label is switched in place" "1" "$(chain_asked aichat.chat.switch.model)"
    check "  not opened in a new window" "0" "$(chain_asked aichat.chat)"
    check "  and nothing is refused"     "0" "$(alerts_count)"
    check "  the window is named"        "$SWIN" "$(cad_pb_get aichatv2_switch_target)"
    check "  and the model handed over"  "$target" "$("$OMC_OMC_SUPPORT_PATH/pasteboard" AICHATV2_MODEL_PATH get)"
done

section "  the tools decision rides with the pick"
# Every cell except gguf-to-gguf rebuilds the agent process, so a changed decision can be honored
# - unlike the first load, this does not detour through the MCP servers dialog, because this
# window decided its servers and working directory when it opened.
chains_reset
sw_reset
sw_window "$MLXREAL" ""
sw_arm_pick "$OTHERMLX" true
omc_run aichat.select.local.model.ok
check "it is still an in-place switch" "1" "$(chain_asked aichat.chat.switch.model)"
check "  with no detour"               "0" "$(chain_asked aichat.mcp.servers)"
check "  and tools stashed for it"     "true" "$(cad_pb_get aichatv2_switch_tools)"

section "  the same model with a different tools decision IS a switch"
# The box means this window's own decision now, so ticking it for the model already loaded is a
# request - "keep this model, give it its tools" - and the unchanged gate has to let it through
# or it answers by discarding it.
chains_reset
sw_reset
sw_window "$MLXREAL" "" false
# Cleared first: the previous section left a value here, and an assertion that reads a key nothing
# in THIS section wrote is an assertion about the last one.
cad_pb_set "aichatv2_switch_tools" ""
cad_pb_set "aichatv2_switcharm_$OMC_ACTIONUI_WINDOW_UUID" "$SWIN|$(/bin/date +%s)"
omc_table_cell 10 5 "$MLXREAL"
omc_control 30 true
omc_run aichat.select.local.model.ok
check "it reaches the switch"       "1" "$(chain_asked aichat.chat.switch.model)"
check "  carrying the new decision" "true" "$(cad_pb_get aichatv2_switch_tools)"

section "  the same model with the same decision is not a switch"
chains_reset
sw_reset
sw_window "$MLXREAL" ""
sw_arm_pick "$MLXREAL" false
omc_run aichat.select.local.model.ok
check "nothing is switched" "0" "$(chain_asked aichat.chat.switch.model)"
check "  and no window opens" "0" "$(chain_asked aichat.chat)"
# An unstamped window stays on the unchanged side: the switch reads an empty stamp as unchanged
# too, so letting a pick through here would respawn an agent for a decision nobody recorded.
chains_reset
cad_pb_set "aichatv2_tools_$SWIN" ""
cad_pb_set "aichatv2_switcharm_$OMC_ACTIONUI_WINDOW_UUID" "$SWIN|$(/bin/date +%s)"
omc_table_cell 10 5 "$MLXREAL"
omc_control 30 true
omc_run aichat.select.local.model.ok
check "and neither is one with no decision recorded" "0" "$(chain_asked aichat.chat.switch.model)"

section "  an agent's window is offered a new window instead"
# The one pair that stays refused, and not for want of a mechanism: an external agent owns its
# session, its context and its tool loop, and priming a local model with the transcript it
# produced would hand it someone else's conversation to continue as its own.
chains_reset
sw_reset
cad_pb_set "aichatv2_modelpath_$SWIN" ""
cad_pb_set "aichatv2_agent_$SWIN" "Claude Code"
cad_pb_set "aichatv2_open_$SWIN" "1"
sw_arm_pick "$MLXDIR" false
alert_answer 0                      # "Open in New Window"
omc_run aichat.select.local.model.ok
check "the user is asked"              "1" "$(alerts_count)"
check "  and told what is running"     "1" "$(alerts_mention "Claude Code")"
check "  in a sentence about agents"   "1" "$(alerts_mention "cannot be moved from an agent")"
check "accepting opens a new window"   "1" "$(chain_asked aichat.chat)"
check "  and switches nothing"         "0" "$(chain_asked aichat.chat.switch.model)"

chains_reset
sw_reset
cad_pb_set "aichatv2_agent_$SWIN" "Claude Code"
# Cleared first, because the key OUTLIVES a picker: it is consumed by the switch handler, which
# does not run in these sections. Asserting it is empty afterwards means "declining armed nothing"
# only if nothing had armed it before.
cad_pb_set "aichatv2_switch_target" ""
sw_arm_pick "$MLXDIR" false
alert_answer 1                      # "Cancel"
omc_run aichat.select.local.model.ok
check "declining leaves everything alone" "0" "$(chain_asked aichat.chat)"
check "  and switches nothing"            "0" "$(chain_asked aichat.chat.switch.model)"
check "  and nothing is left aimed"       ""  "$(cad_pb_get aichatv2_switch_target)"

section "  a target that vanished is refused where the picker is still open"
# Deleted between the scan that listed it and the click. Refused HERE, with the arm put back, so
# the user can choose again in the dialog they are looking at.
chains_reset
sw_reset
sw_window "$MLXREAL" ""
sw_arm_pick "$MODELS/never-existed.gguf" false
omc_run aichat.select.local.model.ok
check "nothing is switched"        "0" "$(chain_asked aichat.chat.switch.model)"
check "  nor opened"               "0" "$(chain_asked aichat.chat)"
check "the user is told"           "1" "$(alerts_count)"
check "and the switch is re-armed" "1" \
    "$(cad_has "$(cad_pb_get "aichatv2_switcharm_$OMC_ACTIONUI_WINDOW_UUID")" "$SWIN")"


# ---------------------------------------------------------------------------
section "the tools decision is the window's, and it survives the switch"
# NOTHING ELSE REMEMBERS IT. After a launch, the decision lives only in the agent's argv, where no
# handler can read it back - so the window stamps it, the picker shows that stamp, and the switch
# carries it. Without the stamp the picker offers an unchecked box and a switch answers "no tools"
# for a conversation that has been using them: agent rebuilt without its servers, generated config
# deleted, nothing said.
sw_reset
sw_window "$MLXREAL" "" true
sw chat_engine_switch "$SWIN" "$OTHERMLX" true
check "a switch with tools on succeeds"    "0" "$?"
check "  and the agent is given its config" "1" "$(cad_has "$(sw_config)" '"--mcp-config"')"
check "  and the window remembers it"       "true" "$(cad_pb_get "aichatv2_tools_$SWIN")"
check "  and the config file exists"        "1" "$([ -f "$(sw_mcp_config)" ] && echo 1 || echo 0)"

sw_reset
sw_window "$MLXREAL" "" true
sw chat_engine_switch "$SWIN" "$OTHERMLX" false
check "turning tools off succeeds"          "0" "$?"
check "  the agent is rebuilt without them" "0" "$(cad_has "$(sw_config)" '"--mcp-config"')"
check "  the window says so"                "false" "$(cad_pb_get "aichatv2_tools_$SWIN")"
check "  and the generated config is gone"  "0" "$([ -f "$(sw_mcp_config)" ] && echo 1 || echo 0)"

section "  and on gguf-to-gguf it is the only thing that can force a respawn"
# That cell keeps the agent alive on purpose - its conversation array carries over a server
# restart - so it re-injects only when the argv would actually differ, which for a switch means
# --mcp-config appearing or going.
sw_reset
sw_window "$GGUF" "8151" true
kept_cfg="$(sw_mcp_config)"
/bin/mkdir -p "$(/usr/bin/dirname "$kept_cfg")"
printf '{"mcpServers":{"kept":{}}}' > "$kept_cfg"
sw chat_engine_switch "$SWIN" "$OTHER" true
check "an unchanged decision keeps the agent" "0" "$(sw_configs)"
check "  and the server still restarts"       "launch" "$(sw_calls)"
# Building a transport regenerates this window's MCP config, or deletes it, as a side effect of
# being asked - so the cell that keeps its agent must not ask.
# CONTENT, not existence: with tools staying on, asking for a transport would REGENERATE this
# file rather than delete it, and an existence check cannot tell the two apart.
check "  and leaves its config file alone"    "1" "$(cad_has "$(/bin/cat "$kept_cfg")" 'kept')"

sw_reset
sw_window "$GGUF" "8151" false
sw chat_engine_switch "$SWIN" "$OTHER" true
check "a changed decision rebuilds it"        "1" "$(sw_configs)"
check "  with the config on the argv"         "1" "$(cad_has "$(sw_config)" '"--mcp-config"')"
check "  still on the window's own port"      "8151" "$(sw_launch_port)"
# This cell reaches the launch through the transport builder rather than calling it directly, so
# it is the one that could pass a retiring engine by accident. It has none: the model it is
# leaving was a server, and that server is TERMed by the launch itself.
check "  and still with nothing retiring"     "" "$(sw_launch_retiring)"
# THE ONE THAT MATTERS. The stop-after-inject step releases the server this window is LEAVING -
# and on this cell the stamped port carries the server just started for the model being switched
# TO. Stopping it here reported success and left a live composer talking to a dead port.
check "  and the server it just started is NOT stopped" "launch" "$(sw_calls)"
check "  so the window keeps its port"        "8151" "$(cad_pb_get "aichatv2_port_$SWIN")"
check "  and the window remembers the change" "true" "$(cad_pb_get "aichatv2_tools_$SWIN")"

section "  a failed switch leaves the decision where it was"
sw_reset
sw_window "$MLXREAL" "" true
STUB_EMPTY_JSON=1
sw chat_engine_switch "$SWIN" "$OTHERMLX" false
check "the switch reports failure"    "1" "$?"
check "and the stamp is put back"     "true" "$(cad_pb_get "aichatv2_tools_$SWIN")"

section "  the picker offers the window's own decision, not the next model's capability"
# THE SEQUENCE IS THE POINT, so this drives the real one: init, a row click, then OK. Continue
# ships disabled and only the click enables it, so every pick goes through a handler that writes
# the tools box from what the TARGET model supports - which is the right question for a first
# load and the wrong one for a switch, where the conversation already has an answer.
#
# The click's write is fed back into the OK handler by hand because the harness's control values
# are inputs, not a live window: in the app the box the user sees IS what OK reads.
TOOLSMLX="$MODELS/Mlx-Tools-Model"
/bin/mkdir -p "$TOOLSMLX"
printf '{}' > "$TOOLSMLX/config.json"
/usr/bin/head -c 512 /dev/zero > "$TOOLSMLX/model.safetensors"
# A template that RENDERS a tool call, which is what the badge and the toggle key off - not a
# vocabulary that merely contains the token.
printf '{"chat_template": "{%% for m in messages %%}{{ m.content }}{%% endfor %%}{%% if tools %%}<tool_call>{%% endif %%}"}' \
    > "$TOOLSMLX/tokenizer_config.json"
check "the fixture is a tools-capable model" "0" \
    "$(cad_call_lib aichat.model.library.sh model_supports_tools "$TOOLSMLX" mlx >/dev/null 2>&1; echo $?)"

pick_row() { # <model> - the click that enables Continue and writes the tools box
    omc_table_cell 10 5 "$1"
    omc_run aichat.select.local.model.selection.changed
}

ui_reset
chains_reset
sw_reset
sw_window "$MLXREAL" "" false                       # a conversation answering WITHOUT tools
cad_pb_set "aichatv2_switcharm_$OMC_ACTIONUI_WINDOW_UUID" "$SWIN|$(/bin/date +%s)"
omc_run aichat.select.local.model.init
pick_row "$TOOLSMLX"
check "a tools-off conversation does not acquire them from the target" "false" "$(ui_value 30)"
omc_control 30 "$(ui_value 30)"
omc_run aichat.select.local.model.ok
check "  and the switch is handed that answer" "false" "$(cad_pb_get aichatv2_switch_tools)"

ui_reset
chains_reset
sw_reset
sw_window "$MLXREAL" "" true                        # ... and one that HAS been using them
cad_pb_set "aichatv2_switcharm_$OMC_ACTIONUI_WINDOW_UUID" "$SWIN|$(/bin/date +%s)"
omc_run aichat.select.local.model.init
pick_row "$TOOLSMLX"
check "a tools-on conversation keeps them"     "true" "$(ui_value 30)"
omc_control 30 "$(ui_value 30)"
omc_run aichat.select.local.model.ok
check "  and the switch is handed that answer" "true" "$(cad_pb_get aichatv2_switch_tools)"

ui_reset
sw_window "$MLXREAL" "" true
cad_pb_set "aichatv2_switcharm_$OMC_ACTIONUI_WINDOW_UUID" "$SWIN|$(/bin/date +%s)"
omc_run aichat.select.local.model.init
pick_row "$OTHERMLX"                                # no tool template at all
check "but only a model that can drive tools may have them" "false" "$(ui_value 30)"

ui_reset
cad_pb_set "aichatv2_switcharm_$OMC_ACTIONUI_WINDOW_UUID" ""
omc_run aichat.select.local.model.init
pick_row "$TOOLSMLX"
check "with nothing armed the capability decides, as it always did" "true" "$(ui_value 30)"

# A window can close while its picker is still open, and its stamps outlive it. The pick then
# falls through to opening a NEW window, which should be offered the ordinary default rather than
# a dead conversation's decision.
ui_reset
sw_window "$MLXREAL" "" false
cad_pb_set "aichatv2_open_$SWIN" ""
cad_pb_set "aichatv2_switcharm_$OMC_ACTIONUI_WINDOW_UUID" "$SWIN|$(/bin/date +%s)"
omc_run aichat.select.local.model.init
pick_row "$TOOLSMLX"
check "a closed window's decision is not carried into a new one" "true" "$(ui_value 30)"
cad_pb_set "aichatv2_open_$SWIN" "1"

# ---------------------------------------------------------------------------
section "picking the model the window already runs changes nothing"
# The picker refuses this as "model unchanged", but it compares the path it LISTED against the
# path the window stamped - and for an MLX model reached through a symlink those differ, because
# the stamp is the PHYSICAL directory mlx-swift-lm has to be given. Comparing after the resolution
# is what stops a pick that changes nothing from killing the agent and re-priming the whole
# conversation.
sw_reset
sw_window "$MLXREAL" "" false
sw chat_engine_switch "$SWIN" "$MLXDIR" false
check "it succeeds"                    "0" "$?"
check "  and injects nothing"          "0" "$(sw_configs)"
check "  launches nothing"             ""  "$(sw_calls)"
check "  and leaves the stamp alone"   "$MLXREAL" "$(cad_pb_get "aichatv2_modelpath_$SWIN")"
# And nothing is repaired on the way out, because nothing is left broken. This branch used to
# re-set the window title: a failed switch wrote "failed to load model" there and left it, while
# the model bar went on naming the model that was still running. The title reports nothing now,
# so a switch that changes nothing writes nothing.
check "  and writes no title"          "0" "$(ui_calls omc_window)"

# And a window with NO decision recorded is unchanged too, whatever the box says - the same rule
# the picker's gate and the gguf-to-gguf rebuild test apply. Nothing knows what an unrecorded
# decision would be changing FROM, so acting on it would respawn an agent for a pick that asked
# for nothing.
sw_reset
sw_window "$MLXREAL" "" false
cad_pb_set "aichatv2_tools_$SWIN" ""
sw chat_engine_switch "$SWIN" "$MLXDIR" true
check "an unrecorded decision is not a change" "0" "$(sw_configs)"
check "  and nothing is launched for it"       ""  "$(sw_calls)"

# ---------------------------------------------------------------------------
section "a load that outruns ten seconds says so in the overlay, and only there"
# THE BUG THIS SECTION EXISTS FOR. wait_for_server used to write "still loading model…" straight
# into the window title, and it was the ONE title write in the whole load that ignored the rule
# every other one obeyed - a window showing a saved conversation keeps its name. So on exactly
# that window the note went in and nothing ever took it out: the switch finished, the model
# answered, and the title still said "still loading model…" until the window was closed.
#
# There is no rule left to obey - the title is the app's name and nobody writes it - so the
# assertion is the flat one: the wait reports through the overlay it was given, and touches the
# title zero times. The stubbed launch above cannot cover this; wait_for_server is only ever
# reached through the real launch, so this drives it directly.
#
# `sleep` is stubbed to nothing so the twelve-second timeout costs milliseconds. Everything else
# is real, including the curl: the port is one no listener should hold, and a health probe that
# unexpectedly SUCCEEDS returns 0 instead of 13 and fails the first check rather than passing
# quietly.
wfs() {
    ( . "$OMC_APP_BUNDLE_PATH/Contents/Resources/Scripts/aichat.server.library.sh" >/dev/null 2>&1
      prefs="${CAD_PREFS_OVERRIDE:-$OMCTEST_WORK/no-such-registry.plist}"
      sleep() { :; }
      wait_for_server "$@" )
}
sw_reset
# The window the bug needed: one with a conversation loaded in it.
cad_pb_set "aichatv2_session_$SWIN" "20260821T000000Z-switch"
wfs "$SWIN" 59321 12 "Tiny-Q4_K_M"
check "a health probe that never answers times out" "13" "$?"
check "  with an alert"                             "1"  "$(alerts_count)"
check "  the slow load is named in the overlay"     "Still loading Tiny-Q4_K_M…" \
    "$(ui_prop "$BASE_CHAT_OVERLAY_ELEM_ID" title "$SWIN")"
check "  and the window title is never written"     "0"  "$(ui_calls omc_window)"
# Without a label there is still something to say. The caller passes LAUNCHED_MODEL_LABEL, which
# is set from the model path, but a wait is not the place to discover it is empty.
sw_reset
wfs "$SWIN" 59321 12
check "an unnamed model still reports progress" "Still loading the model…" \
    "$(ui_prop "$BASE_CHAT_OVERLAY_ELEM_ID" title "$SWIN")"
cad_pb_set "aichatv2_session_$SWIN" ""

# ---------------------------------------------------------------------------
section "stopping one window's server, for real"
# The registry walk the close handler used to own inline. Stubbed everywhere above, so this is the
# only place it runs - and aichat.chat.cancel.sh depends on it now.
#
# The registry is BUILT BY THE REAL REGISTRAR rather than by hand: the two are a pair (one writes
# /server-hosts/<host>/<pid> and /server-info/<pid>/dialog, the other reads them back), and a
# hand-built fixture would let them drift apart and still pass. The "servers" are sleeps, so the
# TERM is real and harmless.
SRVREG="$OMCTEST_WORK/registry.plist"
/bin/rm -f "$SRVREG"
sleep 300 &
fake_server=$!
sleep 300 &
other_server=$!
check "the harness can hold a background process" "1" "$([ -n "$fake_server" ] && [ -n "$other_server" ] && echo 1 || echo 0)"
srv() { CAD_PREFS_OVERRIDE="$SRVREG" cad_call_lib aichat.server.library.sh "$@"; }
srv register_started_server 999 "$fake_server"  "$GGUF"  "$SWIN"              8151 4096 >/dev/null
srv register_started_server 999 "$other_server" "$OTHER" "some-other-window"  8152 4096 >/dev/null

srv stop_window_server "$SWIN" TESTTAG >/dev/null
check "it reports having stopped one" "0" "$?"
# Bounded: a TERM that never lands should fail the assertion below rather than wedge the suite.
waited=0
while /bin/ps -p "$fake_server" >/dev/null 2>&1 && [ "$waited" -lt 10 ]; do sleep 1; waited=$((waited + 1)); done
check "this window's server is gone"  "0" "$(/bin/ps -p "$fake_server" >/dev/null 2>&1 && echo 1 || echo 0)"
check "  and its registry entries too" "" "$(srv chat_switch_probe_dialog "$fake_server")"
check "another window's server is untouched" "1" \
    "$(/bin/ps -p "$other_server" >/dev/null 2>&1 && echo 1 || echo 0)"
check "  and still registered"               "some-other-window" \
    "$(srv chat_switch_probe_dialog "$other_server")"

srv stop_window_server "no-such-window" TESTTAG >/dev/null
check "a window with no server says so" "1" "$?"
check "  and leaves the registry alone" "some-other-window" \
    "$(srv chat_switch_probe_dialog "$other_server")"
kill -TERM "$other_server" 2>/dev/null

# ---------------------------------------------------------------------------
section "an engine about to stop is not charged against the one starting"
# The scan behind --fit-target, for real. A llama-server keeps its --fit decision for its whole
# life, so what this counts at launch is what that window lives with: charging it for an MLX model
# the switch is about to release cost a 31B arrival its context and made the first message after
# the switch fail outright.
#
# ASSERTED ON THE SCAN, NOT ON --fit-target, and deliberately. The target the policy finally emits
# depends on this machine's cap, its RAM and whatever the developer happens to have loaded - a
# heavily loaded host takes the CPU-fallback branch, which states no target at all - so an
# assertion there would prove different things on different machines and nothing on some. The
# scan is the part this change touched and the part with an answer that does not depend on the
# host: whatever it says with the engine running, it must say the same thing without it.
#
# The stand-ins are scripts NAMED mlx-agent, because the scan reads argv and nothing else, and
# they carry the two argvs acp_transport_json.py actually produces for the MLX engine:
# `acp --model <dir>` with tools off, and `acp --model <dir> --mcp-config <sessions>/<win>/...`
# with tools on. The difference is the whole point of the second rule below, and a fixture that
# invented its own flag order would test neither.
FAKEBIN="$OMCTEST_WORK/fakebin"
/bin/mkdir -p "$FAKEBIN"
/bin/cat > "$FAKEBIN/mlx-agent" <<'FAKE_AGENT'
#!/bin/sh
# Holds its argv and nothing else. The trap is what keeps `sleep` from outliving a killed parent.
sleep 600 &
fake_child=$!
trap 'kill "$fake_child" 2>/dev/null; exit 0' TERM
wait "$fake_child"
FAKE_AGENT
/bin/chmod +x "$FAKEBIN/mlx-agent"

# Big enough that the weights term is not floored away by the integer division: du reports KB, and
# the charge is (KB / 1024) * 1.15 + 768, so a 512 KB fixture would be indistinguishable from an
# empty one and the discount could drop the wrong half of the sum without failing.
RETIRING="$MODELS/Retiring-Mlx-Model"
/bin/mkdir -p "$RETIRING"
/usr/bin/head -c 16777216 /dev/zero > "$RETIRING/model.safetensors"

# The scan reports two numbers - everything live, and the part of it that is retiring - because
# what may be discounted is a question about RAM against the Metal cap, which it cannot see.
srv_total()    { srv scan_engine_footprints "$1" "$2" | /usr/bin/awk '{print $1}'; }
srv_retiring() { srv scan_engine_footprints "$1" "$2" | /usr/bin/awk '{print $2}'; }

fake_agents=""
# fake_agent_start [window-uuid] - a stand-in with the tools-off argv, or the tools-on one when a
# window is named. Waits (bounded) for it to be visible in ps with its argv intact.
fake_agent_start() {
    local cfg="$HOME/Library/Application Support/Cadabra/Sessions/$1/mcp-config.json"
    if [ -n "$1" ]; then
        "$FAKEBIN/mlx-agent" acp --model "$RETIRING" --mcp-config "$cfg" &
    else
        "$FAKEBIN/mlx-agent" acp --model "$RETIRING" &
    fi
    local pid=$! waited=0
    while ! /bin/ps -p "$pid" -o args= 2>/dev/null | /usr/bin/grep -q -- "--model $RETIRING"; do
        [ "$waited" -ge 10 ] && break
        sleep 1; waited=$((waited + 1))
    done
    fake_agents="$fake_agents $pid"
}
fake_agents_stop() {
    local pid waited=0
    for pid in $fake_agents; do kill -TERM "$pid" 2>/dev/null; done
    while [ -n "$(/bin/ps -o args= -p $fake_agents 2>/dev/null | /usr/bin/grep -- "--model $RETIRING")" ] \
          && [ "$waited" -lt 10 ]; do sleep 1; waited=$((waited + 1)); done
    fake_agents=""
}
# NO `trap ... EXIT` HERE, though the temptation is obvious. omctest installs its own EXIT trap in
# THIS shell when a file is run standalone (omctest_prepare_env), and a bare trap replaces it - one
# full isolated $HOME and every named pasteboard leaked per run. Tests/lib.test.cadabra.sh records
# that exact mistake having been made and fixed once already.
#
# Nothing is lost by leaving it out: a stand-in's --model directory lives inside the scratch tree,
# so once omctest removes that tree the `[ -d ]` guard in the scan drops the process anyway, and
# `sleep 600` bounds it regardless.

fp_base=$(srv_total)
check "the scan answers with a number" "1" \
    "$([ "$fp_base" -ge 0 ] 2>/dev/null && echo 1 || echo 0)"
check "  and nothing is retiring when nothing was named" "0" "$(srv_retiring)"

fake_agent_start
fp_one=$(srv_total)
check "a live engine is counted"         "1" "$([ "$fp_one" -gt "$fp_base" ] && echo 1 || echo 0)"
check "  by its weights, not a flat fee" "1" "$([ "$fp_one" -gt $(( fp_base + 768 )) ] && echo 1 || echo 0)"
check "naming it as retiring accounts for exactly what it cost" \
    "$(( fp_one - fp_base ))" "$(srv_retiring "$RETIRING")"
check "  and a model nothing is running for" "0" "$(srv_retiring "$MODELS/Absent-Model")"

# The ambiguity that makes the path rule a discount rather than a subtraction. Two windows on one
# MLX model produce two identical argvs with tools off, so the process that is leaving cannot be
# identified - and discounting anyway would free budget nothing is about to release, which is the
# GPU over-commit this whole policy exists to prevent.
fake_agent_start
fp_two=$(srv_total)
check "two engines are counted twice"    "1" "$([ "$fp_two" -gt "$fp_one" ] && echo 1 || echo 0)"
check "  and neither can be told apart"  "0" "$(srv_retiring "$RETIRING")"

# Unless one of them says which window it belongs to. An agent launched with tools carries its own
# session directory, and no other window's argv can contain that path - so the count stops being
# the question.
fake_agent_start "$SWIN"
fp_three=$(srv_total)
check "a third engine is counted too"    "1" "$([ "$fp_three" -gt "$fp_two" ] && echo 1 || echo 0)"
check "the window's own agent is identified among identical siblings" \
    "$(( fp_three - fp_two ))" "$(srv_retiring "$RETIRING" "$SWIN")"

fake_agents_stop
# THE CASE THE COUNT GETS WRONG RATHER THAN GIVES UP, and it needs exactly ONE engine running to
# show: a window whose agent has already died still carries its model stamp, so the single live
# process on that model belongs to somebody ELSE and is not about to free anything. Naming a window
# is a claim the caller can find its own agent, so failing to find it is an answer - not a reason to
# fall back to the count.
#
# Asserted with one stand-in on purpose. An earlier version of this check ran with three still
# alive, where the answer was 0 because the PATH rule had given up on the ambiguity - it would have
# passed just as well without the rule it was named after.
fake_agent_start
fp_lonely=$(srv_total)
check "one engine is running the retiring model" "1" \
    "$([ "$fp_lonely" -gt "$fp_base" ] && echo 1 || echo 0)"
check "  and the path rule alone would discount it" \
    "$(( fp_lonely - fp_base ))" "$(srv_retiring "$RETIRING")"
check "but a window whose agent is gone discounts nothing" \
    "0" "$(srv_retiring "$RETIRING" "OMCTEST-no-such-window")"

fake_agents_stop
# Re-measured rather than compared against fp_base: those readings are seconds apart, and any real
# engine on this machine starting or stopping in between would fail an equality that has nothing
# to do with this code.
check "a retiring model nothing is running discounts nothing" "0" "$(srv_retiring "$RETIRING")"

# ---------------------------------------------------------------------------
section "  and only as much of it as the machine can carry twice at once"
# The discount is not a promise that the memory is free: the outgoing engine dies when the element
# reconciles the injected config, which cannot happen until the launch RETURNS - and the launch
# returns after wait_for_server, which allows up to 300 s for a large model. Both engines are
# resident for that whole load, so what may be planned as free is bounded by the RAM the Metal cap
# leaves outside itself. Without the bound, a big enough retiring model turns a switch into
# minutes of genuine GPU over-commit, which is the failure the sizing policy exists to prevent.
#
# Written as its own function precisely so this is arithmetic a test can state, rather than four
# lines buried in a path whose emitted --fit-target depends on what the developer has loaded.
check "a discount inside the slack is granted whole" "6000" \
    "$(srv retiring_discount_mib 6000 32768 24248)"
check "one past it is cut to the slack"              "8520" \
    "$(srv retiring_discount_mib 12616 32768 24248)"
check "  which is 26 percent of RAM, not a constant" "4260" \
    "$(srv retiring_discount_mib 12616 16384 12124)"
check "nothing retiring is nothing discounted"       "0" \
    "$(srv retiring_discount_mib 0 32768 24248)"
# A cap above physical RAM cannot happen today (cap is 74% of it), but the floor is what keeps a
# future change to that ratio from producing a NEGATIVE discount, which would silently inflate the
# reserve instead of lowering it.
check "and a slack that went negative floors at zero" "0" \
    "$(srv retiring_discount_mib 6000 16384 20000)"

# ---------------------------------------------------------------------------
section "cumulative: no handler wrote to a view id the window does not declare"
check "no undeclared ids" "" "$(ui_unknown_writes)"
check "no table clobbered by a bare value write" "" "$(ui_suspect_writes)"

omctest_end
